---
sidebar: sidebar 
permalink: concept_searching_assets.html 
summary: 高度な検索手法を使用すると、探しているアセットを見つけることができます。 
keywords: asset page, objects, search, advanced, alerts 
---
= 資産とアラートを検索するためのヒントとヒント
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
監視対象環境内のデータやオブジェクトを検索する場合は、複数の検索手法を使用できます。

* * ワイルドカード検索 *
+
文字を使用して、複数文字のワイルドカード検索を実行できます。たとえば、 _applic * n_ は _application_ を返します。

* * フレーズ検索 *
+
フレーズは、「 VNX LUN 5 」などの二重引用符で囲まれた単語のグループです。二重引用符を使用して、名前または属性にスペースを含むドキュメントを検索できます。

* * 論理演算子 *
+
論理演算子 OR 、 AND 、 NOT を使用すると、複数のキーワードを組み合わせて複雑なクエリを作成できます。

+
または

+
OR 演算子は、デフォルトの結合演算子です。

+
2 つのキーワードの間にブール演算子がない場合は、 OR 演算子が使用されます。

+
OR 演算子は、 2 つのキーワードをリンクし、どちらかの条件がドキュメントに存在する場合に一致するドキュメントを検索します。

+
たとえば、 _storage や NetApp_searches と指定すると、 _storage_or_NetApp_._ を含むドキュメントが検索されます。

+
一致するキーワードの数が多いドキュメントほどスコアが高くなります。

+
および

+
AND 演算子を使用すると、両方の検索語が 1 つのドキュメント内に存在するドキュメントを検索できます。たとえば、 _storage と NetApp_searches は、 _storage_ と _NetApp_ の両方を含むドキュメントを検索します。

+
との代わりに、記号 * & * を使用できます。

+
ありません

+
NOT 演算子を使用すると、 NOT のあとのキーワードを含むすべてのドキュメントが検索結果から除外されます。たとえば、 _storage NOT NetApp_searches を指定すると、 _storage_ のみを含み、かつ _NetApp_ でないドキュメントが検索されます。

+
NOT という単語の代わりに、記号 * ！ * を使用できます。



検索では大文字と小文字は区別されません。



== インデックスキーワードを使用して検索します

インデックスキーワードの数が多い検索では、スコアが高くなります。

検索文字列は、スペースで複数の検索キーワードに分けて表示されます。たとえば、「 storage aurora netapp 」という検索文字列は、「 storage 」、「 aurora 」、「 netapp 」の 3 つのキーワードに分けられ、3 つのキーワードをすべて使用して検索が実行されます。これらのキーワードのほとんどに一致するドキュメントのスコアが最も高くなります。入力する情報が多いほど、検索結果の方が適しています。たとえば、ストレージを名前やモデルで検索できます。

検索結果は、カテゴリごとに上位 3 件まで表示されます。想定しているオブジェクトが見つからない場合は、検索文字列にキーワードを追加して検索結果を絞り込むことができます。

次の表に、検索文字列に追加できるインデックスキーワードのリストを示します。

|===
| カテゴリ | インデックスキーワード 


| ストレージ | "ストレージ"
名前
ベンダー
モデル 


| ストレージプール | "ストレージプール"
名前
ストレージの名前
ストレージのIPアドレス
ストレージのシリアル番号
ストレージベンダー
ストレージモデル
関連付けられているすべての内部ボリュームの名前
関連付けられているすべてのディスクの名前 


| 内部ボリューム | "内部ボリューム"
名前
ストレージの名前
ストレージのIPアドレス
ストレージのシリアル番号
ストレージベンダー
ストレージモデル
ストレージプールの名前
関連付けられているすべての共有の名前
関連付けられているすべてのアプリケーションの名前 


| ボリューム | "ボリューム"
名前
ラベル
すべての内部ボリュームの名前
ストレージプールの名前
ストレージの名前
ストレージのIPアドレス
ストレージのシリアル番号
ストレージベンダー
ストレージモデル 


| ストレージノード | "ストレージノード"
名前
ストレージの名前
ストレージのIPアドレス
ストレージのシリアル番号
ストレージベンダー
ストレージモデル 


| ホスト | "ホスト"
名前
IP アドレス
関連付けられているすべてのアプリケーションの名前 


| データストア | "データストア"
名前
Virtual Center IPの略
すべてのボリュームの名前
すべての内部ボリュームの名前 


| 仮想マシン | 「仮想マシン」
名前
DNS名
IP アドレス
ホストの名前
ホストのIPアドレス
すべてのデータストアの名前
関連付けられているすべてのアプリケーションの名前 


| スイッチ（標準と NPV ） | "スイッチ"
IP アドレス
WWN
名前
シリアル番号
モデル
ドメインID
ファブリックの名前
ファブリックのWWN 


| アプリケーション | "アプリケーション"
名前
テナント
基幹業務部門
ビジネスユニット
プロジェクト 


| テープ | "テープ"
IP アドレス
名前
シリアル番号
ベンダー 


| ポート | "ポート"
WWN
名前 


| ファブリック | "ファブリック"
WWN
名前 


| Storage Virtual Machine （ SVM ） | "ストレージ仮想マシン"
名前
UUID 
|===