---
sidebar: sidebar 
permalink: concept_audit.html 
keywords: audit, users, activities 
summary: 監査では、 Cloud Insights システムのシステムアクティビティとユーザアクティビティが確認できます。 
---
= 監査


[role="lead"]
想定外の変更を特定するために、 Cloud Insights システムとそのユーザアクティビティの監査証跡を表示できます。

Cloud Insights では、システムまたはユーザに影響する変更について監査エントリが生成されます。これらの変更には、次のもの

* ログインしています
* パスの許可または許可解除
* 許可されたパスの更新
* グローバルなポリシーまたはしきい値を設定します
* データコレクタの追加または削除
* データコレクタの開始と停止
* データコレクタのプロパティを更新して
* タスクの追加、編集、または削除
* アプリケーショングループを削除しています
* デバイスの ID を識別または変更する


監査システムにアクセスするには、次の手順を実行します。

.手順
. Cloud Insights メニューで、 * Admin > Audit * をクリックします
+
監査ページが表示され、各監査エントリについて次の詳細が示されます。

+
** * Time * - 変更が行われた日時
** * User * - ユーザー・アカウントの役割（ guest 、ユーザー、または管理者）
** * ip * - 監査エントリに関連付けられた IP アドレス
** * Action * - 監査エントリのアクティビティのタイプ
** * Details * - 監査エントリの詳細




データコレクタやアプリケーションなどのリソースに影響するユーザアクティビティがある場合、それらのリソースのランディングページへのリンクが詳細に含まれます。

* 注 * データコレクタを削除すると、データコレクタに関連するユーザアクティビティの詳細にデータコレクタのランディングページへのリンクが表示されなくなります。



== 監査エントリの表示

監査エントリを表示する方法はいくつかあります。

* 特定の期間（ 1 時間、 3 時間、 24 時間、 3 日間、 7 日間）を選択することで、監査エントリを表示できます。 Cloud Insights では、選択した期間について、最大 1 、 000 件の違反が表示されます。
* 列見出しで矢印をクリックすると、表内の列のソート順序を昇順（上矢印）または降順（下矢印）に変更できます。
+
デフォルトでは、エントリが降順に表示されます。

* フィルタボックスを使用して、テーブルに必要なエントリだけを表示できます。

