---
sidebar: sidebar 
permalink: concept_cs_agent_requirements.html 
summary: エージェントとして使用するサーバまたは VM が、最小要件を満たしている必要があります 
keywords: agent, Linux, requirements, docker, browsers, permissions, Network, Cloud Secure 
---
= ワークロードセキュリティエージェントの要件
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
実行する必要があります link:task_cs_add_agent.html["エージェントをインストールします"] データコレクタから情報を取得します。Agent をインストールする前に、お使いの環境がオペレーティングシステム、 CPU 、メモリ、およびディスクスペースの要件を満たしていることを確認してください。


NOTE: ストレージワークロードセキュリティは、Cloud Insights フェデラルエディションでは使用できません。

[cols="36,60"]
|===
| コンポーネント | Linux 要件 


| オペレーティングシステム | 次のいずれかのライセンスバージョンを実行しているコンピュータ。

Red Hat Enterprise Linux 7.x、8.x 64ビット、SELinux
CentOS 7.x 64ビット、SELinux
CentOS 8 Stream、SELinux
Ubuntu 20から22 64ビット
Rocky 8.x 64ビット、Rocky 9.x 64ビット、SELinux
SUSE Linux Enterprise Server 15 SP3、SUSE Linux Enterprise Server 15 SP4、SUSE 15 SP3上のSELinux

このコンピュータでは、他のアプリケーションレベルのソフトウェアを実行しないでください。専用のサーバを使用することを推奨します。 


| コマンド | インストールには「unzip」が必要です。また、インストール、スクリプトの実行、およびアンインストールには、「sudo su–」コマンドが必要です。 


| CPU | 4 個の CPU コア 


| メモリ | 16GB の RAM 


| 使用可能なディスクスペース | ディスクスペースは次の方法で割り当てる必要があります。
/opt/netapp 35GB（最小）

/optがNASストレージからマウントされたフォルダである場合は、ローカルユーザーがこのフォルダにアクセスできることを確認してください。ローカルユーザにこのフォルダへのアクセス権がない場合、エージェントまたはデータコレクタのインストールが失敗する可能性があります。を参照してください link:task_cs_add_agent.html#troubleshooting-agent-errors["トラブルシューティング"] 詳細については、を参照してください。 


| ネットワーク | 100 Mbps~1 Gbpsイーサネット接続、静的IPアドレス、すべてのデバイスへのIP接続、およびワークロードセキュリティインスタンスへの必要なポート（80または443） 
|===
ワークロードセキュリティエージェントは、Cloud Insights Acquisition UnitやAgentと同じマシンにインストールできます。ただし、これらを別々のマシンにインストールすることを推奨します。これらが同じマシンにインストールされている場合は、次のようにディスク領域を割り当ててください。

|===


| 使用可能なディスクスペース | 50～55 GB
Linuxの場合は、次の方法でディスクスペースを割り当てる必要があります。
/opt/ネットアップ25~30GB
/var/log/netapp 25GB 
|===


== その他の推奨事項

* ONTAP システムとエージェントマシンの両方の時刻を、 *Network Time Protocol （ NTP; ネットワークタイムプロトコル） * または *Simple Network Time Protocol （ SNTP ） * を使用して同期することを強くお勧めします。




== Cloud Network Access Rules の略

USベースの*ワークロード・セキュリティー環境の場合：

[cols="5*"]
|===
| プロトコル | ポート | 宛先 | 方向（ Direction ） | 説明 


| TCP | 443年 | <site_name>.cs01.cloudinsights.netapp.com
<site_name>.c01.cloudinsights.netapp.com
<site_name>.c02.cloudinsights.netapp.com | アウトバウンド | Cloud Insights へのアクセス 


| TCP | 443年 | gateway.c01.cloudinsights.netapp.com
agentlogin.cs01.cloudinsights.netapp.com | アウトバウンド | 認証サービスへのアクセス 
|===
欧州*ベースのワークロード・セキュリティー環境の場合：

[cols="5*"]
|===
| プロトコル | ポート | 宛先 | 方向（ Direction ） | 説明 


| TCP | 443年 | <site_name>.cs01-eu-1.cloudinsights.netapp.com
<site_name>.c01-eu-1.cloudinsights.netapp.com
<site_name>.c02-eu-1.cloudinsights.netapp.com | アウトバウンド | Cloud Insights へのアクセス 


| TCP | 443年 | gateway.c01.cloudinsights.netapp.com
agentlogin.cs01-eu-1.cloudinsights.netapp.com | アウトバウンド | 認証サービスへのアクセス 
|===
APACベースの*ワークロード・セキュリティ環境の場合：

[cols="5*"]
|===
| プロトコル | ポート | 宛先 | 方向（ Direction ） | 説明 


| TCP | 443年 | <site_name>.cs01-ap-1.cloudinsights.netapp.com
<site_name>.c01-ap-1.cloudinsights.netapp.com
<site_name>.c02-ap-1.cloudinsights.netapp.com | アウトバウンド | Cloud Insights へのアクセス 


| TCP | 443年 | gateway.c01.cloudinsights.netapp.com
agentlogin.cs01-ap-1.cloudinsights.netapp.com | アウトバウンド | 認証サービスへのアクセス 
|===


== ネットワーク内ルール

を追加する場合に注意してくださいlink:task_add_collector_svm.html#permissions-when-adding-via-cluster-management-ip["CSUser"]が必要です。このユーザには、ONTAP 管理LIFへのSSHアクセスが必要です。

[cols="5*"]
|===
| プロトコル | ポート | 宛先 | 方向（ Direction ） | 説明 


| TCP | 389（LDAP）
636（LDAPS / START-TLS） | LDAP サーバ URL | アウトバウンド | LDAP に接続します 


| TCP | 443年 | クラスタまたはSVMの管理IPアドレス（SVMコレクタの設定に応じて） | アウトバウンド | ONTAP との API 通信 


| TCP | 35000~55000 | SVM データ LIF の IP アドレス | インバウンド | FPolicy イベントのための ONTAP との通信 


| TCP | 7. | SVM データ LIF の IP アドレス | アウトバウンド | ONTAP とワークロードセキュリティ間の単一方向。エージェントが SVM LIF に ping を送信します。 


| SSH | 22. | クラスタ管理 | アウトバウンド | CIFS / SMBユーザブロックに必要です。 
|===


== システムのサイジング

を参照してください link:concept_cs_event_rate_checker.html["イベントレートチェッカー"] サイジングに関する情報のドキュメント
