---
sidebar: sidebar 
permalink: concept_acquisition_unit_requirements.html 
summary: Acquisition Unit として使用するサーバまたは VM が最小要件を満たしている必要があります 
keywords: AU, acquisition unit, RAU, requirements, sizing 
---
= Acquisition Unit の要件
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
インフラのデータコレクタ（ストレージ、 VM 、ポート、 EC2 など）から情報を取得するには、 Acquisition Unit （ AU ）をインストールする必要があります。Acquisition Unit をインストールする前に、オペレーティングシステム、 CPU 、メモリ、およびディスクスペースが要件を満たしていることを確認してください。



== 要件

|===


| コンポーネント | Linux 要件 | Windows 要件 


| オペレーティングシステム | 次のいずれかのライセンスバージョンを実行しているコンピュータ。

* CentOS（64ビット）：7.2～7.9、Stream 8、Stream 9
* Debian (64ビット): 9と10
* Oracle Enterprise Linux（64ビット）：7.5～7.9、8.1～8.4
* Red Hat Enterprise Linux（64ビット）：7.2～7.9、8.1～8.7、9.1
*ロッキー9.0、9.1
* Ubuntu Server：18.04および20.04 LTS

このコンピュータでは、他のアプリケーションレベルのソフトウェアを実行しないでください。専用のサーバを使用することを推奨します。

<<<<>> SELinux
SELinuxを使用している場合は、Acquisition Unitシステムで次のコマンドを実行することを推奨します。

 _sudo semanage fcontext -a -t usr_t "/opt/NetApp/cloudinsights（/.*）？"_
 _sudo restorecon -R /opt/NetApp/cloudinsights _
=========
>>>>>> メイン | 次のいずれかのライセンスバージョンを実行しているコンピュータ。

* Microsoft Windows 10 64ビット
* Microsoft Windows Server 2012
* Microsoft Windows Server 2012 R2
* Microsoft Windows Server 2016
* Microsoft Windows Server 2019
* Microsoft Windows Server 2022
* Microsoft Windows 11


このコンピュータでは、他のアプリケーションレベルのソフトウェアを実行しないでください。専用のサーバを使用することを推奨します。 


| CPU | 2個のCPUコア | 同じ 


| メモリ | 8GB の RAM | 同じ 


| 使用可能なディスクスペース | 50 GB（100 GBを推奨）
Linuxの場合は、次の方法でディスクスペースを割り当てる必要があります。
/opt/netapp 10 GB（大規模環境では20 GB）
/var/log/netapp 40 GB（大規模環境では80 GB）
/tmpインストール中に1 GB以上の空き容量が必要です | 50GB 


| ネットワーク | 100Mbps/1Gbpsイーサネット接続、静的IPアドレス、およびAcquisition Unitから*。.cloudinsights.netapp.comまたはCloud Insights環境（\https：//<environment_id>.c01.cloudinsights.netapp.com）へのポート80または443の接続が必要です。Acquisition Unitと各Data Collectorの要件については、の手順を参照してください link:data_collector_list.html["Data Collector"]。

組織でインターネットアクセスにプロキシを使用する必要がある場合は、組織のプロキシ動作を理解し、 Cloud Insights が機能するように特定の例外を要求する必要があります。たとえば、デフォルトでアクセスがブロックされ、特定のWebサイト/ドメインへのアクセスのみが例外で許可されていますか。その場合は、次のドメインを例外リストに追加する必要があります。

*.cloudinsights.netapp.com

詳細については、「プロキシについて」を参照してください link:task_troubleshooting_linux_acquisition_unit_problems.html#considerations-about-proxies-and-firewalls["こちらをご覧ください"] または link:task_troubleshooting_windows_acquisition_unit_problems.html#considerations-about-proxies-and-firewalls["こちらをご覧ください"]。 | 同じ 


| 権限 | Acquisition Unit サーバに対する sudo 権限
/tmp は EXEC 機能でマウントする必要があります。 | Acquisition Unit サーバに対する管理者権限が必要です 


| ウィルススキャン |  | インストール時に、すべてのウィルススキャンソフトウェアを完全に無効にする必要があります。インストール後に、 Acquisition Unit ソフトウェアで使用するパスをウィルススキャンから除外する必要があります。 
|===


== その他の推奨事項

* 正確な監査およびデータレポートを作成するためには、 * Network Time Protocol （ NTP ；ネットワークタイムプロトコル） * または * Simple Network Time Protocol （ SNTP ） * を使用して Acquisition Unit マシンの時間を同期することを強く推奨します。




== サイジングについて

Cloud Insights Acquisition Unit は 8GB のメモリと 50GB のディスクスペースしかないので、まずは大規模な環境に備えるために次の項目を確認してください。

次のことを期待していますか？

* この Acquisition Unit 上で、 2500 台を超える仮想マシン、または 10 台の大規模（ 2 ノード以上）の ONTAP クラスタ、 Symmetrix 、 HDS / HPE VSP/XP アレイを検出できるか？
* この Acquisition Unit に合計 75 個以上のデータコレクタを導入しますか？


上記の「はい」回答ごとに、 8 GB のメモリと 50 GB のディスク容量を AU に追加することをお勧めします。たとえば、「はい」と答えた場合、 150GB 以上のディスクスペースを備えた 24GB のメモリシステムを導入する必要があります。Linux の場合、ログの場所に追加するディスクスペース。

サイジングに関するその他の情報については、ネットアップサポートにお問い合わせください。



== Federal Editionの追加要件

* Cloud Insights フェデラルエディションクラスタにAcquisition Unitをインストールする場合は、基盤となるオペレーティングシステムに適切なエントロピーのソースが必要です。Linuxシステムでは、これは通常、_rng-tools_をインストールするか、ハードウェア乱数生成（RNG）を使用して行われます。Acquisition Unitマシンでこの要件が満たされていることを確認するのは、お客様の責任です。

