---
sidebar: sidebar 
permalink: cs_restrict_user_access.html 
keywords: alert, snapshot,  attack 
summary: Cloud Secure を使用すると、破壊の疑いがある場合にユーザアクセスを制限できます 
---
= ユーザアクセスをブロックしています
:allow-uri-read: 


[role="lead"]
攻撃が検出されると、Cloud Secure はファイルシステムへのユーザアクセスをブロックすることで攻撃を停止できます。アクセスは、自動応答ポリシーを使用して自動的にブロックするか、アラートまたはユーザの詳細ページから手動でブロックできます。

ユーザアクセスをブロックする場合は、ブロック期間を定義する必要があります。選択した期間が終了すると、ユーザアクセスが自動的にリストアされます。アクセスブロックは、SMBプロトコルとNFSプロトコルの両方でサポートされています。

SMBおよびホストマシンのIPアドレスに対してユーザが直接ブロックされているため、NFSに対して攻撃がブロックされます。これらのマシンの IP アドレスは、 Cloud Secure で監視されているいずれかの Storage Virtual Machine （ SVM ）へのアクセスがブロックされます。

たとえば、Cloud Secure は10個のSVMを管理し、自動応答ポリシーはそのうち4つのSVMに対して設定されているとします。攻撃の原因が4つのSVMのいずれかである場合、10個のSVMすべてでユーザのアクセスがブロックされます。元の SVM では引き続き Snapshot が作成されます。

SMB用に設定されたSVMが4つあり、NFS用に設定されたSVMが残り2つのSVMがNFSとSMB両方に対して設定されている場合、4つのSVMのいずれかで攻撃が発生すると、すべてのSVMがブロックされます。



== ユーザアクセスブロックの前提条件

この機能を使用するには、クラスタレベルのクレデンシャルが必要です。

クラスタ管理者のクレデンシャルを使用している場合、新しい権限は不要です。

ユーザに付与された権限を持つcsuserなどのカスタムユーザを使用している場合は、次の手順に従ってCloudSecureにブロックユーザへの権限を付与します。

クラスタクレデンシャルを持つ csuser の場合、 ONTAP コマンドラインから次の手順を実行します。

....
security login role create -role csrole -cmddirname "vserver export-policy rule" -access all
security login role create -role csrole -cmddirname set -access all
security login role create -role csrole -cmddirname "vserver cifs session" -access all
security login role create -role csrole -cmddirname "vserver services access-check authentication translate" -access all
security login role create -role csrole -cmddirname "vserver name-mapping" -access all
security login role create -role csrole -cmddirname "cluster show" -access readonly
....


== 機能を有効にする方法

* Cloud Secure で、[*Admin]>[Automated Response Policies]>[Response Policy Settings]>[Block User Access*]の順に選択します。
* [Enable Block User Access]を[enable_enabled_]に設定します。




== 自動ユーザアクセスブロックの設定方法

* 新しい攻撃ポリシーを作成するか、既存の攻撃ポリシーを編集します。
* 攻撃ポリシーを監視する SVM を選択します。
* [ユーザーファイルアクセスをブロックする]チェックボックスをオンにします。この機能は、このオプションを選択すると有効になります。
* [ ユーザーアクセスの制限 ] で、適用する制限のモードを選択します。
* [Time Period]で、ブロッキングを適用する時間を選択します。
* 自動ユーザブロッキングをテストするには、を使用して攻撃をシミュレートします link:concept_cs_attack_simulator.html["シミュレートされたスクリプト"]。




== システム内にブロックされているユーザーがいるかどうかを確認する方法

* アラートリストページでは、ユーザがブロックされた場合に画面上部のバナーが表示されます。
* バナーをクリックすると、[Users]ページが表示され、ブロックされているユーザのリストが表示されます。
* [Users]ページには、「User/IP Access」という名前のカラムがあります。この列には、ユーザブロッキングの現在の状態が表示されます。




== ユーザアクセスを手動で制限および管理します

* アラートの詳細画面またはユーザの詳細画面に移動して、これらの画面からユーザを手動でブロックまたは復元できます。




== ユーザアクセス制限履歴

［アラートの詳細とユーザーの詳細］ページのユーザーパネルで、ユーザーのアクセス制限履歴（時間、アクション（ブロック、ブロック解除）、期間、実行されたアクション）の監査を表示できます。 手動/自動、およびNFSの影響を受けるIP。



== 機能を無効にする方法

この機能はいつでも無効にできます。システム内に制限のあるユーザがいる場合は、アクセスを先にリストアする必要があります。

* Cloud Secure で、[*Admin]>[Automated Response Policies]>[Response Policy Settings]>[Block User Access*]の順に選択します
* 無効にするには、[ブロックユーザーアクセスを有効にする]をオフにします。


この機能はすべてのページで非表示になります。



== NFSのIPを手動でリストア

Cloud Secure トライアルの期限が切れた場合、またはエージェント / コレクタがダウンした場合に、 ONTAP から IP を手動でリストアするには、次の手順を実行します。

. SVM のすべてのエクスポートポリシーをリストします。
+
....
contrail-qa-fas8020::> export-policy rule show -vserver <svm name>
             Policy          Rule    Access   Client                RO
Vserver      Name            Index   Protocol Match                 Rule
------------ --------------- ------  -------- --------------------- ---------
svm_s_____a default         1       nfs3,    cloudsecure_rule,     never
                                     nfs4,    10.11.12.13
                                     cifs
svm_s_____a default         4       cifs,    0.0.0.0/0             any
                                     nfs
svm_s_____a test            1       nfs3,    cloudsecure_rule,     never
                                     nfs4,    10.11.12.13
                                     cifs
svm_s_____a test            3       cifs,    0.0.0.0/0             any
                                     nfs,
                                     flexcache
4 entries were displayed.
....
. 「cloudsecure_rule」をクライアント一致として持つSVMのすべてのポリシーのルールを削除するには、対応するRuleIndexを指定します。通常、Cloud Secure ルールは1になります。
+
 contrail-qa-fas8020::*> export-policy rule delete -vserver <svm name> -policyname * -ruleindex 1
. Cloud Secure ルールが削除されていることを確認します（オプションの確認手順）。
+
....
contrail-qa-fas8020::*> export-policy rule show -vserver <svm name>
             Policy          Rule    Access   Client                RO
Vserver      Name            Index   Protocol Match                 Rule
------------ --------------- ------  -------- --------------------- ---------
svm_suchitra default         4       cifs,    0.0.0.0/0             any
                                     nfs
svm_suchitra test            3       cifs,    0.0.0.0/0             any
                                     nfs,
                                     flexcache
2 entries were displayed.
....




== トラブルシューティング

|===
| 問題 | 試してみてください 


| 一部のユーザーは制限されていませんが、攻撃があります。 | 1. SVM の Data Collector と Agent が _RUNNING であることを確認します。Data Collector と Agent が停止している場合、 Cloud Secure はコマンドを送信できません。2. これは、ユーザが以前に使用されていない新しい IP を持つマシンからストレージにアクセスした可能性があるためです。制限は、ユーザがストレージにアクセスする際に使用するホストの IP アドレスを介して行われます。UI （ Alert Details > Access Limitation History for this User > Affected IP ）で、制限されている IP アドレスのリストを確認します。IP が制限された IP と異なるホストからストレージにアクセスしている場合、ユーザは制限されていない IP を介してストレージにアクセスできます。IP が制限されているホストからアクセスしようとすると、ストレージにアクセスできなくなります。 


| [Restrict Access] を手動でクリックすると、「このユーザの IP アドレスはすでに制限されています」というメッセージが表示されます。 | 制限する IP はすでに別のユーザから制限されています。 


| ポリシーを変更できませんでした。理由：このコマンドは許可されていません。 | csuserを使用している場合は、上記のようにユーザに権限が与えられているかどうかを確認します。 
|===