---
sidebar: sidebar 
permalink: concept_faq.html 
keywords: FAQ, Frequently asked questions, performance, troubleshooting 
summary:  
---
= パフォーマンスのトラブルシューティング


[role="lead"]
この FAQ では、 Cloud Insights のパフォーマンスのトラブルシューティングに関する一般的な質問を取り上げています



== 環境内のすべての Greedy リソースのリストを作成するにはどうすればよいですか。

Cloud Insights の相関分析は、「指定された」サービスパスの Greedy リソースと劣化したリソースの特定に役立ちます。相関フィーチャーの生成された解析は ' 各オブジェクトを表示しながらリアルタイムで実行されます提供される分析によって、パフォーマンスの問題のトラブルシューティングやルート原因の特定に必要な時間が大幅に短縮されます。定義されたパフォーマンスポリシーで発生した違反の調査は、 Greedy リソースやパフォーマンスが低下したリソースを検出するためのエントリポイントの 1 つです。Cloud Insights の異常検出機能は、サービスの停止を招く前に、アプリケーションインフラで消費の多いリソースやデグレード状態のリソースを特定する、よりプロアクティブなアプローチとしても使用できます。最新のクエリ機能を使用しているウィジェットとダッシュボードのどちらも、想定 IOPS （ Greedy ）、利用率、レイテンシを超えるリソースのフィルタリング、ソート、可視化に役立ちます。



== Cloud Insights では、パフォーマンスの問題を 1 箇所で診断できますか。

はい。Cloud Insights のパフォーマンスのトラブルシューティングには、さまざまな方法があります。Cloud Insights には、複数のアラート方法があります。SNMP 、 syslog 、 E メールで送信されるアラートがよく使用されます。E メールで送信されたアラートを使用すると、 Cloud Insights 内の影響を受けるリソースをクリックして起動できます。グローバル検索ウィンドウでは、リソース名を入力するだけで状況の分析を開始できます。

Cloud Insights の Violation Dashboard では、イベント数、期間、時刻に基づいて作業に優先順位を付けることができる。アラートの種類には、レイテンシ、 IOPS 、利用率、重大度、ビジネスユニット、アプリケーションなどがあります。

Cloud Insights の相関分析を使用すると、管理者は影響を受けたリソースとオブジェクトを比較して、 IOPS 、レイテンシ、利用率、 CPU 、 BB クレジットへの影響を判断できます。

Cloud Insights の最新の異常検出機能とイーサネット監視機能は、サービスの停止や停止に発展する前にリソースの異常動作を検出するための積極的でプロアクティブなアプローチを提供します。

Cloud Insights のクエリテクノロジとウィジェットダッシュボードでは、データセンター内の問題領域を対象とした体系的なビューで詳細を特定できます。



== clustered Data ONTAP への 7-Mode の移行で、 Cloud Insights を使用できますか。

はい。 Cloud Insights は、既存のワークロードの需要や移行後の検証を把握するのに非常に役立ちます。今日のデータセンターの最新化における Cloud Insights の役割により、変更管理シミュレーション、移行前の最適化計画、適切なサービス階層の定義が可能になります。Cloud Insights では、数回のクリックで、数千もの NFS 共有とファイバチャネルパスのビジネスへの影響を簡単に収集して関連付けます。Cloud Insights は、移行から機器更改に至るまで、適切な規模への移行を確実に実施し、計画外のサービス停止を軽減します。



== Cloud Insights のパフォーマンス監視はどのような「リアルタイム」ですか。

Cloud Insights は、オンプレミスとハイブリッドクラウドの両方のデータセンター管理でほぼリアルタイムとみなされます。データソースのポーリングはより頻繁に実行されるように構成できますが、ほとんどのユーザーは、 5 分未満のほとんどのデバイスでパフォーマンス収集間隔を設定することで、分析上の大きなメリットを得ることができません。収集頻度を増やすと、管理対象のオブジェクトや実行される分析に不要な負荷がかかる可能性があります。もちろん、より詳細な収集が必要な場合もあります。 Cloud Insights では、構成可能なデバイスインベントリやパフォーマンスポーリング間隔など、お客様固有のデータセンター環境のニーズに合わせた完全な柔軟性を実現できます。



== 「合計」が「読み取り」と「書き込み」で異なるのはなぜですか？

場合によっては、カウンタの合計が、そのカウンタの読み取りと書き込みの合計と等しくないことがあります。この問題が発生する可能性があるのは、いくつかの場合です。

IOPS ：ストレージアレイやその他のアセットでは、読み取りと書き込みに加えて、ワークロードのデータフローとは関係のない内部処理も処理されます。「システム」、「メタデータ」、または単に「その他」の処理と呼ばれることもあり、 Snapshot 、重複排除、スペースの再割り当てなどの内部プロセスに起因することがあります。その場合は、特定のアセットのシステム処理量を確認するために、合計 IOPS から読み取り IOPS と書き込み IOPS の合計を引いて算出します。読み取り IOPS と書き込み IOPS の合計は、データフローに直接関連する合計 IOPS です。

Latency ：処理の合計応答時間（レイテンシ）は時間加重平均であるため、書き込み応答時間よりも短いと報告されることがあります。I/O ワークロードは多くの場合書き込み処理よりも多くの読み取り処理で構成され、書き込みでは一般にレイテンシが大きくなります。たとえば、平均レイテンシが 5 ミリ秒で 10 個の読み取り処理を実行したワークロードの場合、平均レイテンシが 10 ミリ秒の 5 つの書き込み処理を実行した場合、合計加重平均レイテンシは、読み取り回数と平均読み取りレイテンシの合計で計算されます。 書き込み数に平均書き込みレイテンシを掛けた値を、 I/O 処理の合計数で割った値。たとえば、（ 10 × 5 + 5 × 10 ） / （ 10 + 5 ） = 6.33 ミリ秒のようになります。
