---
sidebar: sidebar 
permalink: concept_faq.html 
keywords: FAQ, Frequently asked questions, general questions, questions 
summary:  
---
= Cloud Insights に関するよくある質問です


[role="lead"]
この FAQ では、 Cloud Insights に関する一般的な質問に回答しています。



== Cloud Insights はいつ導入されましたか？

Cloud Insights は、現在の業界で最も成熟したインフラ監視製品をベースにしており、 10 年以上にわたって積極的な開発を続けています。以前の名称は「 Onaro 」または「 SANscreen 」で、 OnCommand ポートフォリオ製品スイートに加わる際に SANscreen 名が変更され、現在は「 Cloud Insights 」または「 Onaro 」または「 Cloud Insights 」と呼ばれています。



== 環境への Cloud Insights の導入にどれくらいの時間がかかりますか。

Cloud Insights は、ソフトウェアのダウンロードにすぎません。ソフトウェアは、 2 台の専用の仮想サーバまたは物理サーバにインストールされます。一般的なインストールはわずか 2 時間で完了し、インベントリ、容量、パフォーマンスのデータの提供はほぼ即座に開始されます。パフォーマンスとベストプラクティスのポリシー、ユーザアノテーション、およびコスト情報の設定を追加する場合は、計画についてさらに検討する必要があります。



== Cloud Insights には、エージェント、コレクタ、またはプローブが必要ですか。

Cloud Insights は完全なエージェントレスであり、エージェント、タップ、プローブを使用する必要はありません。すべてのデバイス検出は読み取り専用で、アウトオブバンドおよび IP 経由で実行されます。



== Cloud Insights はどのようにしてデバイスを検出し、接続しますか。

Cloud Insights のセットアップでは、データセンター環境にすでに存在する標準の API とプロトコルが使用されます。エージェントやプローブは必要ありません。SSH 、 HTTP 、 SMIS 、および CLI は、ほんの一例です。デバイスエレメントマネージャがすでに存在する場合（たとえば、 Dell EMC Unisphere ）、 Cloud Insights はエレメントマネージャと通信して既存の環境データをキャプチャします。ほとんどのデバイス検出では、 IP アドレスと読み取り専用のユーザ名とパスワードのみが必要です。これらのデバイスディスカバリは、 Cloud Insights の VMware データコレクタなどの「 1 対多」で実行できます。Cloud Insights は、 VMware vCenter を検出することで、すべての ESXi ホストとそれに関連付けられた VM を 1 つの IP アドレスとクレデンシャルで検出します。



== Cloud Insights にはプロフェッショナルサービスが必要ですか。それは利用でき、それらは何を提供するか。

中規模の環境では、導入、構成、統合に * プロフェッショナル・サービス * を推奨し、さまざまなカスタム・レポート作成やデータ検証を可能にします。Cloud Insights チームとアカウントエンゲージメントマネージャーとの短い話し合いは、どのサービスが最も効果的かを判断するのに役立ちます。



== Cloud Insights では、新機能や機能強化のために更新プログラムをどのくらいの頻度でリリースしますか。

Cloud Insights の複数のバージョンに対応した製品アップデートとサービスパックが用意されています。メジャーリリースまたはマイナーリリースは、通常、数か月ごとに提供され、新しいデバイスサポートやファームウェアのリリース頻度が高くなっています。どちらも support.netapp.com のダウンロードサイトから入手できます。メーカーから頻繁に提供される新しいディスクモデルなどの特定の更新は、 Cloud Insights ソフトウェアに自動的にプッシュアウトされます。また、 Cloud Insights データコレクタデバイスの収集については、開発の修正または更新の直後にサイトでパッチを適用することができます。



== Cloud Insights 管理チームは、新しいデータコレクタの要求にどのように優先順位を付けますか。

Cloud Insights の製品管理チームは、お客様のすべての機能強化と相互運用性機能に関するリクエスト（ IFR ）を積極的に追跡します。各リクエストの詳細は、実現可能性について評価され、お客様のニーズと戦略的なビジネスへの全体的な影響に基づいて優先順位が付けられます。リクエストはいったん承認されると、対応レベルに基づいてサイズが決定され、将来の開発に向けてスケジュールされます。Cloud Insightss の開発プロセスは即応性に優れた性質を備えており、定期的にリリースする以外にも、新しいデータコレクタを定期的に利用できます。ネットアップのアカウント担当者は、お客様からのお問い合わせや、新しいリクエストの送信にご協力いただけます。データコレクタには、 Cloud Insights をアップグレードすることなく、サイト上でパッチを適用できます。



== 私の会社は Linux で完全に動いています。Cloud Insights は Linux で動作しますか。

はい。 Cloud Insights は、最新のサービスパックプラットフォームで Red Hat Enterprise Linux 7 と CentOS 7 に加え、 64 ビットの Windows Server 2008 R2 、 2012 、または 2012 R2 をサポートしています。



== Cloud Insights は、インターネットにアクセスできないセキュアな環境に適していますか。

はい。 Cloud Insights は、 Fortune 500 にランクインした上位 10 社の企業や、世界中の主要な銀行、医療、研究、政府機関によって使用されています。Cloud Insights は、米国の軍事共通アクセスカード（ CAC ）をサポートし、地理的に分散した環境や、ファイアウォールを多用する環境に対応するソリューションを提供します。



== OnCommand Unified Manager （ OCUM ）が clustered 解決策の管理 であることを私は聞き続けています。Cloud Insights も使用する理由を教えてください。

OnCommand Unified Manager は、ストレージアレイの「デバイス管理」レイヤで動作し、 clustered Data ONTAP （ cDOT ）アレイとそのクラスタインターコネクトに関するインシデントおよびイベントベースの詳細な分析を提供します。Cloud Insights は、 7-Mode 、 clustered Data ONTAP 、およびその他のサードパーティ製アレイで構成されるオンプレミス環境とグローバルに分散した環境を包括的に表示します。仮想マシンからスピンドルに至るまでエンドツーエンドの可視性を提供することで、容量、パフォーマンス、コストモデリングのトレンドと予測の履歴を把握し、データセンター管理に対するプロアクティブなサービス品質アプローチを促進できます。



== 自動化 Storefront に記載されている Cloud Insights セカンダリ ETL とは何ですか？

一部の Cloud Insights 自動化 Storefront レポートダウンロードで参照される「セカンダリ ETL 」の要件は、取得したデータの抽出、変換、読み込み（ ETL ）を実行して Cloud Insights データウェアハウスにデータを格納するために使用する、開発されたプロフェッショナルサービスの実装です。

セカンダリ ETL プロセスの主な目的は、より複雑なレポートの生成を高速化したり、毎日実行するようにスケジュールしたりできるように、「バッチ」データをプリフェッチすることです。

このセカンダリ ETL は、 Cloud Insights Data Warehouse 管理ガイドで詳しく説明されている、「 1 日に 1 回」推奨される ETL に加えて行われます。

ネットアッププロフェッショナルサービスでは、セカンダリ ETL スクリプトを構成して、既存の Cloud Insights レポートスケジュール、自動バックアップ、拡張性、またはその他のシステムパフォーマンスアクティビティへの影響を回避することを認定しています。ETL スクリプトの作成やデータ検証のニーズについては、ネットアップの営業担当者にお問い合わせのうえ、ネットアップのプロフェッショナルサービスがどのようにサポートされるかをご相談ください。追加情報
