---
sidebar: sidebar 
permalink: insights_overview.html 
keywords: insight, greedy, degraded, impacted, impacting, impactful, impact, resources, consuming, workload, ttf, time to full, k8s, kubernetes, namespace 
summary: 分析情報から、リソースの使用状況とトレンド分析を確認できます。 
---
= 分析
:allow-uri-read: 


[role="lead"]
分析情報を使用すると、リソースの使用状況や他のリソースへの影響、時間のかかる分析などを確認できます。

さまざまなインサイトをご利用いただけます。[Dashboards]>[Insights（インサイト）]に移動して、ダイビングを開始します。アクティブなインサイト（現在発生しているインサイト）は、メインタブで表示するか、非アクティブなインサイト（_Inactive Insights）タブで表示できます。非アクティブなインサイトとは、以前はアクティブだったものの、もう発生していないインサイトです。



== Insightのタイプ



=== 負荷のある共有リソース

影響の大きいワークロードは、共有リソース内の他のワークロードのパフォーマンスを低下させる可能性があります。これにより、共有リソースに負荷がかかります。Cloud Insights には、環境内のリソースの飽和と影響の調査に役立つツールが用意されています。 link:insights_shared_resources_under_stress.html["詳細はこちら。"]



=== Kubernetesネームスペースのスペースが不足しています

スペース不足Insightで実行されているKubernetesネームスペースのワークロードについて、スペース不足になる可能性がある状況をKubernetesネームスペースで確認できます。各スペースがフルになるまでの推定日数も示されます。 link:insights_k8s_namespaces_running_out_of_space.html["詳細はこちら。"]



=== ONTAP コールドストレージを再利用します

ONTAP コールドストレージの再利用_Insightは、ONTAP システム上のボリュームについて、コールド容量、潜在的なコスト/電力削減、推奨される対処方法に関するデータを提供します。 link:insights_reclaim_ontap_cold_storage.html["詳細はこちら。"]


NOTE: これは_Preview_featureであり、改善が行われると時間の経過とともに変更される場合があります。 link:/concept_preview_features.html["詳細はこちら。"] Cloud Insights プレビューフィーチャーについて
