---
sidebar: sidebar 
permalink: pre-requisites_for_k8s_operator.html 
keywords: telegraf, installation, install, agent, telegraf agent, kubernetes, eks, operator, k8s 
summary: Cloud Insights は、 Kubernetes で統合データを収集するエージェントとして Telegraf をサポートしています。 
---
= NetApp Kubernetes監視オペレータをインストールまたはアップグレードする前に
:toc: macro
:hardbreaks:
:toclevels: 2
:allow-uri-read: 
:toc: 
:nofooter: 
:toclevels: 2
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
をインストールまたはアップグレードする前に、この情報をお読みください。 link:task_config_telegraf_agent_k8s.html["Kubernetes監視オペレータ"]。



=== 前提条件

|===
| コンポーネント | 要件 


| Kubernetes のバージョン | Kubernetes v1.20以上： 


| Kubernetesディストリビューション | AWS Elastic Kubernetes Service（EKS）
Azure Kubernetes Service （ AKS ）
Google Kubernetes Engine （ GKE ）
Red Hat OpenShift のサービスです
Rancher Kubernetes Engine （ RKE ）
VMware Tanzu の 


| Linux OS | Cloud Insightsは、Arm64アーキテクチャで実行されているノードをサポートしていません。

ネットワーク監視：Linuxカーネルバージョン4.18.0以上を実行している必要があります。Photon OSはサポートされていません。 


| ラベル | Cloud Insights では、 Linux を実行している Kubernetes ノードの監視をサポートしています。 Kubernetes ノードセレクタを指定して、これらのプラットフォームで次の Kubernetes ラベルを検索します。

Kubernetes v1.20以上：kubernetes.io/os=Linux
Rancher + cattle.ioをオーケストレーション/ Kubernetesプラットフォームとして使用：cattle.io / os = Linux 


| コマンド | curlコマンドとkubectlコマンドが使用可能である必要があります。;最良の結果を得るには、これらのコマンドをパスに追加してください。 


| 接続性 | kubectl CLIはターゲットのKubernetesクラスタと通信するように設定し、Cloud Insights環境にインターネット接続できるようにしておきます。

インストール中にプロキシの背後にいる場合は、 link:/task_config_telegraf_agent_k8s.html#configuring-proxy-support["プロキシサポートを設定しています"] Operatorインストールのセクション。

監査およびデータレポートを正確に作成するには、Network Time Protocol（NTP；ネットワークタイムプロトコル）またはSimple Network Time Protocol（SNTP；簡易ネットワークタイムプロトコル）を使用してAgentマシンの時刻を同期します。 


| その他 | OpenShift 4.6以降で実行している場合は、次のリンクを参照してください。task_config_telegraf_agent_k8s.html # OpenShift-instructions [OpenShift Instructionsこれらの前提条件を満たしていることを確認することに加えて。 


| APIトークン | Operatorを再デプロイする場合(つまり、Operatorを更新または置換する場合)は、新しいAPIトークンを作成する必要はありません。前のトークンを再利用できます。 
|===


=== オペレータの設定

新しいバージョンの演算子では、最も一般的に変更される設定は_AgentConfiguration_customリソースで構成できます。オペレータを配備する前に、_operator-config.yaml_fileを編集して、このリソースを編集できます。このファイルには、一部の設定例がコメントアウトされています。のリストを参照してください link:telegraf_agent_k8s_config_options.html["使用可能な設定"] 演算子の最新バージョン。

次のコマンドを使用してオペレータを配置した後で、このリソースを編集することもできます。

 kubectl -n netapp-monitoring edit AgentConfiguration
展開したオペレータのバージョンがAgentConfigurationをサポートしているかどうかを確認するには、次のコマンドを実行します。

 kubectl get crd agentconfigurations.monitoring.netapp.com
「Error from server (NotFound)」というメッセージが表示された場合は、AgentConfigurationを使用する前にオペレータをアップグレードする必要があります。



=== 公差と接線（Tolerations and Taints）

NetApp-ci-telegraf-ds_、_NetApp-CI-fluent-bit-ds_、および_NetApp-CI-net-observer-l4-DS_DaemonSetsは、すべてのノードのデータを正しく収集するために、クラスタ内のすべてのノードでポッドをスケジュールする必要があります。オペレータは、いくつかの既知の*テイント*に耐えられるように設定されています。ノードにカスタムのtaintsを設定して、すべてのノードでポッドが実行されないようにしている場合は、それらのtaintsに* toleration *を作成できます link:telegraf_agent_k8s_config_options.html["（_AgentConfiguration_）をクリックします"]。クラスタ内のすべてのノードにカスタムテイントを適用した場合は、オペレータの導入に必要な許容範囲を追加して、オペレータポッドをスケジュールおよび実行できるようにする必要があります。

Kubernetesの詳細はこちらをご覧ください link:https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/["塗料および耐性"]。

に戻ります link:task_config_telegraf_agent_k8s.html["* NetApp Kubernetes監視オペレータのインストール*ページ"]
