---
sidebar: sidebar 
permalink: security_admin_tool.html 
summary: Cloud Insights は、リリースライフサイクル全体を通じてセキュリティのベストプラクティスに従います。 
keywords: security, risk, protection 
---
= securityadminツール
:allow-uri-read: 


[role="lead"]
CIには、セキュリティを強化してInsight環境を運用できるセキュリティ機能が含まれています。暗号化、パスワードハッシュの強化、内部ユーザパスワードの変更、パスワードの暗号化と復号化を行うキーペアの変更などが含まれます。

機密データを保護するために、インストールまたはアップグレード後にデフォルトのキーとAcquisitionユーザのパスワードを変更することを推奨します。

データソースで暗号化されたパスワードはCloud Insights に保存されます。では、ユーザがデータコレクタ設定ページでパスワードを入力したときに、公開鍵を使用してパスワードが暗号化されます。Cloud Insights には、データコレクタのパスワードの復号化に必要な秘密鍵がありません。データコレクタのパスワードの復号化に必要なデータコレクタの秘密鍵があるのは、Acquisition Unitだけです。



== アップグレードとインストールに関する考慮事項

Insightシステムにデフォルト以外のセキュリティ設定が含まれている場合（パスワードのキーが変更されている場合など）は、セキュリティ設定をバックアップする必要があります。新しいソフトウェアをインストールするか、ソフトウェアをアップグレードする場合によっては、システムをデフォルトのセキュリティ設定に戻します。システムがデフォルトの設定に戻ったら、システムを正常に動作させるために、デフォルト以外の設定をリストアする必要があります。



== Acquisition Unit上でセキュリティを管理する

SecurityAdminツールを使用すると、Cloud Insights のセキュリティオプションを管理でき、Acquisition Unitシステム上で実行できます。セキュリティの管理には、キーとパスワードの管理、作成したセキュリティ設定の保存とリストア、またはデフォルト設定への設定のリストアが含まれます。



== 作業を開始する前に

セキュリティ設定タスクを実行するには、AUシステムに対する管理者権限が必要です。

このタスクについて、SecurityAdminツールは、Acquisition Unitシステムの次のいずれかの場所にあります。

* * windows-C：\Program Files\SANscreen\securityadmin\bin\securityadmin.bat
* * Linux -/bin/oci-securityadmin.sh


.手順
* * SecurityAdminツールをインタラクティブモード（-i）で起動します。
+
次のオプションが表示されます。

* バックアップ
+
すべてのパスワードとキーが格納されているバックアップのzipファイルを作成し、そのファイルをユーザが指定した場所、または次のデフォルトの場所に置きます。

+
....
Windows - C:\Program Files\SANscreen\backup\vault
Linux - /var/log/netapp/oci/backup/vault
....
* リストア
+
作成したバックアップのzipファイルをリストアします。リストアすると、すべてのパスワードとキーがバックアップ作成時の既存の値に戻ります。

+
Restoreは、複数のサーバ上のパスワードとキーを同期するために使用できます。たとえば、-AUで暗号化キーを変更する-ヴォールトのバックアップを作成する-バックアップをAUSごとにバックアップを復元する

* 暗号化キーを変更します
+
デバイスのパスワードの暗号化または復号化に使用するAU暗号化キーを変更します。

+
暗号化キーを変更した場合、アップグレードまたはインストール後にリストアできるように、新しいセキュリティ設定をバックアップしておく必要があります。

* パスワードを更新します
+
「acquisition」ユーザアカウントのパスワードを変更します。

+
パスワードを変更した場合、必要に応じて新しいセキュリティ設定をリストアできるように、新しいセキュリティ設定をバックアップしておく必要があります。

* デフォルトにリセットします
+
acquisitionユーザのパスワードとacquisitionユーザの暗号化キーをデフォルト値にリセットします。デフォルト値はインストール時に指定したパスワードと暗号化キーです。

* 終了します
+
SecurityAdminツールを終了します。



設定するオプションを選択し、画面の指示に従います。
