---
sidebar: sidebar 
permalink: task_dc_emc_unisphere_rest.html 
keywords: data collector, Unisphere, EMC 
summary: Dell EMC Unisphere RESTデータコレクタの構成 
---
= Dell EMC Unisphere RESTデータコレクタの構成
:toc: macro
:hardbreaks:
:toclevels: 2
:allow-uri-read: 
:toc: 
:toclevels: 2
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
このデータコレクタは、Dell EMC Unisphere for PowerMax/VMAX 3管理システムからインベントリデータとパフォーマンスデータを取得します。

Dell/EMCでは、Unisphere 10.0までボリュームごとの統計情報を導入していませんでした。このデータコレクタは9.2.0以降をサポートしていますが、ボリューム統計情報が存在しないため、収集できません。

1つのUnisphere for VMAX/PowerMaxインスタンスで1つ以上のSymmetrix 3以降のストレージアレイを管理できます。このコレクタは、すべてのアレイを検出しようとしています。

データコレクタを設定するには、UnisphereサーバのIPアドレス/FQDN、ポート8443へのTCP接続、およびユーザ名とパスワードが必要です。



== 要件

* UnisphereサーバのIPアドレス/完全修飾ドメイン名
* ユーザ名とパスワード
* ポート8443




== 設定

[cols="2*"]
|===
| フィールド | 説明 


| UnisphereサーバのIPアドレス | UnisphereサーバのIPアドレスまたは完全修飾ドメイン名 


| Unisphereポート | デフォルトは8443です 


| ユーザ名 | Unisphereサーバのユーザー名 


| パスワード | Unisphereサーバのパスワード 
|===


== 高度な設定

[cols="2*"]
|===
| フィールド | 説明 


| インベントリポーリング間隔（分） | デフォルトは40分です。 


| パフォーマンスポーリング間隔（秒） | パフォーマンスのポーリング間隔 


| 「除外」または「含める」を選択してリストを指定します | VM を含めるか除外するかを指定します 


| インベントリフィルタデバイスリスト | フィルタリングするVMのリスト（カンマ区切り、または値にカンマが使用されている場合はセミコロンで区切った） 


| Unisphereパフォーマンスポーリング間隔（秒） | デフォルトは300秒です 
|===


== トラブルシューティング

このデータコレクタで問題が発生した場合の対処方法を次に示します。



=== 在庫

[cols="2*"]
|===
| 問題 | 次の操作を実行します 


| エラー：ユーザ認証に失敗しました。 | このデバイスのクレデンシャルが正しいことを確認してください。 
|===
追加情報はから入手できます link:concept_requesting_support.html["サポート"] ページまたはを参照してください link:https://docs.netapp.com/us-en/cloudinsights/CloudInsightsDataCollectorSupportMatrix.pdf["Data Collector サポートマトリックス"]。
