---
sidebar: sidebar 
permalink: task_troubleshooting_general_problems.html 
summary: Cloud Insights の一般的なトラブルシューティングのヒント。 
keywords: troubleshooting, problems, browser, login, log in, accessing, access to, Trident, qtree, quota 
---
= Cloud Insights の一般的な問題のトラブルシューティング
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
ここでは、 Cloud Insights のトラブルシューティングに関する推奨事項を示します。

も参照してください link:task_troubleshooting_linux_acquisition_unit_problems.html["Linux Acquisition Unit の問題のトラブルシューティング"] および link:task_troubleshooting_windows_acquisition_unit_problems.html["Windows Acquisition Unit の問題のトラブルシューティング"]。



== ログインの問題

|===
| * 問題： * | * これを試みなさい : * 


| Cloud Insights は 5 分ごとにログアウトします | 396149d67edd166e53b49c38f4b707ba 


| e4ff2e59dd571d2bbd5a906b6fad2546 | a9a216fbb1fb9d774e7cedfcf74c00cf 


| Cloud Insights に招待されましたが、「認証されていません」というメッセージが表示されます。 | 199017f1d912993f091b6b969d3442ad 


| 176f8c6fa466059df49f2717c021d306 | 7a8624fb56224e907698f45ef2e4cc47 


| 数日後に自動的にログアウトされました。 | ed6e79e2f9b9c201ed834c6efeb7f356 


| 「ログインを許可されていません」というエラーメッセージが表示されます。 | acf29dcaa06698c29122cba5402e3145 


| その他のログインエラーです | Chrome で incognito モードを試すか、ブラウザの履歴、クッキー、およびキャッシュをクリアします。
別のブラウザプロファイル（例 Chrome - ユーザーを追加します）。 
|===


== その他の問題

|===


| *質問：* | *回答 ：* 


| qtreeのハードクォータがクエリに正しく表示されていますが、ソフトクォータがボリュームの合計容量として表示されています。正解ですか？ | 設定されたクォータとして表示されるのは、手動で設定するかTridentで設定したハードクォータのみです。ハードクォータを指定しない場合、qtreeの容量は内部ボリュームの容量になります。 


| 同じqtreeにソフトクォータとハードクォータの両方を手動で設定していますが、表示される合計容量はハードクォータです。Is that correct？ | ○（ハードクォータが指定されている場合は、合計容量として表示されます） 


| Cognosのレポートスケジュールの時間を入力すると、スケジュールの時間に「m」が余分に表示されることがあります。たとえば、時刻を「02:15 PM」と入力すると、「02:15 PMM」（またはPMM）という余分な文字が追加されます。外をクリックすると、「2:15 AM」に変わります。

レポートを保存することはできますが、保存したレポートを再度開くと、スケジュール時刻にAMとPMのどちらを入力したかに関係なく、スケジュール時刻はAM（午前）と表示されます。 | 「AM」または「PM」の文字を完全に入力しないように注意して、スケジュール時刻を再入力します。「AM」は「A」、「PM」は「P」と入力するだけで十分です。余分な文字が表示されない場合は、スケジュール時刻が正しく設定されます。 
|===


== リソース

その他のトラブルシューティングのヒントについては、を参照してください link:https://kb.netapp.com/Advice_and_Troubleshooting/Cloud_Services/Cloud_Insights["ネットアップナレッジベース"] （サポートサインインが必要です）。

その他のサポート情報については、 Cloud Insights を参照してください link:concept_requesting_support.html["サポート"] ページ

アクティブな Cloud Insights サブスクリプションがある場合は、次のサポートオプションを使用できます。

link:https://www.netapp.com/us/contact-us/support.aspx["電話"]
link:https://mysupport.netapp.com/site/cases/mine/create?serialNumber=95001014387268156333["サポートチケット"]

詳細については、を参照してください https://docs.netapp.com/us-en/cloudinsights/concept_requesting_support.html["Cloud Insights サポートドキュメント"]。
