---
sidebar: sidebar 
permalink: task_dc_ceph_storage.html 
keywords: data collector, ceph 
summary: Ceph データコレクタの設定。 
---
= Ceph ストレージデータコレクタ


[role="lead"]
Cloud Insights は、 Ceph ストレージデータコレクタを使用して、 Ceph ストレージプラットフォームからインベントリデータを検出します。



== 用語集

Cloud Insights は、 Ceph ストレージデータコレクタを使用してインベントリ情報を取得します。Cloud Insights では、取得したアセットのタイプごとに、そのアセットに使用される最も一般的な用語が表示されます。このデータコレクタを表示またはトラブルシューティングするときは、次の用語に注意してください。

[cols="2*"]
|===
| ベンダー / モデルの用語 | Cloud Insights の用語 


| プール | ストレージプール 


| ファイルシステム | 内部ボリューム 


| OSD | バックエンド LUN 
|===
注：これらは一般的な用語の対応のみを示したものであり、このデータソースのすべてのケースを表しているとは限りません。



== 要件

* Ceph 管理者の IP アドレス
* 管理者のユーザ名とパスワード
* ポート要件： SSH ポート 22




== 設定

[cols="2*"]
|===
| フィールド | 説明 


| Ceph 管理 IP アドレス | Ceph ストレージのの IP アドレス 


| ユーザ名 | Ceph ストレージシステム管理者ユーザアカウントのユーザ名 


| パスワード | 管理者ユーザアカウントのパスワード 
|===


== 高度な設定

[cols="2*"]
|===
| フィールド | 説明 


| インベントリのポーリング間隔（分） | インベントリのポーリング間隔。デフォルトは 60 分です。 


| SSH ポート | デフォルトはポート 22 です。 
|===


== トラブルシューティング

このデータコレクタで問題が発生した場合の対処方法を次に示します。



==== 在庫

[cols="2*"]
|===
| 問題 | 次の操作を実行します 


| コマンドがありません | ユーザーにデバイス上で以下に示すコマンドを実行する権限があることを確認します * Ceph 管理ツールがインストールされていることを確認します。次のコマンドを実行してください： rpm -q Ceph -common.x86_64 * ウィザードで使用されている認証情報を確認します 


| 設定が無効です | * プールがシステムに設定されていることを確認し、次のコマンドを実行してみます。 Ceph OSD lsplus-f json -pretty * ウィザードで使用されているクレデンシャルとデバイスクレデンシャルが一致していることを確認します 
|===
追加情報はから入手できます link:concept_requesting_support.html["サポート"] ページまたはを参照してください link:https://docs.netapp.com/us-en/cloudinsights/CloudInsightsDataCollectorSupportMatrix.pdf["Data Collector サポートマトリックス"]。
