---
sidebar: sidebar 
permalink: task_create_performance_policies.html 
keywords: performance policy, performance, thresholds, alerts, preference, delete, SVM, VM 
summary: しきい値を設定するパフォーマンスポリシーを作成 
---
= パフォーマンスポリシーによるアラート生成


[role="lead"]
パフォーマンスポリシーを作成して、ネットワーク内のリソースに関連する問題についてユーザに通知するアラートをトリガーするしきい値を設定します。たとえば、ストレージプールの合計使用率が 60% を超えたときにアラートをトリガーするパフォーマンスポリシーを作成できます。

次のオブジェクトのパフォーマンスポリシーを作成できます。

[cols="4*"]
|===


| データストア | ディスク | ハイパーバイザー | 内部ボリューム 


| ポート | qtree | ストレージ | ストレージノード 


| ストレージプール | SVM | VMDK です | VM 
|===


== パフォーマンスポリシーを作成する

監視しているオブジェクトに関連する指標のしきい値を設定したパフォーマンスポリシーを作成できます。デフォルトでは、パフォーマンスポリシーは作成時に指定したタイプのすべてのオブジェクトに適用されます。特定のアセットまたは一連のアセットのみをパフォーマンスポリシーに含める場合は、アノテーションを作成します。

パフォーマンスポリシーでアノテーションを使用する場合、ポリシーを作成する前にアノテーションが存在している必要があります。

監視している 1 つ以上のデバイスが設定したしきい値を超えたときに通知するパフォーマンスポリシーを作成します。システムに、要件を満たすグローバルポリシーがすでに含まれている場合や、アノテーションを使用したポリシーがデバイスにアノテーションを適用した場合でも機能する可能性があります。

.手順
. Cloud Insights メニューバーで、 * Manage > Performance Policies * をクリックします
+
パフォーマンスポリシーページが表示されます。ポリシーはオブジェクト別に表示され、リストに表示されている順序で評価されます。

. パフォーマンスポリシーページで、 * + パフォーマンスポリシー * をクリックします
+
[ * ポリシーの追加 * ] ダイアログが表示されます。

. ［ * ポリシー名 * ］ フィールドに、ポリシーの名前を入力します。
+
オブジェクトのすべてのポリシー名で一意の名前を使用する必要があります。たとえば、内部ボリュームの「 Latency 」という名前の 2 つのポリシーを使用することはできませんが、内部ボリュームの「 Latency 」ポリシーと別のボリュームの「 Latency 」ポリシーを使用できます。ベストプラクティスとしては、オブジェクトタイプに関係なく、すべてのポリシーに一意の名前を常に使用することを推奨します。

. [ タイプ * のオブジェクトに適用（ Apply to Objects of Type * of type ） ] リストから、ポリシーが適用されるオブジェクトのタイプを選択する。
+
仮想マシン * を選択します。

. 必要に応じて、 * とアノテーションリスト * からアノテーションタイプを選択し、 * アノテーション値 * ボックスにアノテーションの値を入力して、そのアノテーションが設定されたオブジェクトのみにポリシーを適用します。
. 「 * Apply after a Window of * 」から、しきい値違反を示すアラートを生成するタイミングを選択します。
+
* 最初の発生 * しきい値を初めて超えたときにアラートをトリガーします。それ以外のオプションでは、しきい値を超えたあと、その状態のまま一定の時間を経過した時点でアラートがトリガーされます。

. [* with severity*] リストから、違反の重大度を選択します。
+
デフォルトでは、ポリシー違反に関する E メールアラートはグローバル E メールリストの受信者に送信されます。この設定を上書きして、特定のポリシーのアラートを特定の受信者に送信するように設定することができます。

. Create alert if * セクションで、パフォーマンスカウンタとオペレータを選択し、値を入力してしきい値を作成します。
+
[* + しきい値 * ] をクリックして、ポリシーにカウンタを追加します。

. [ 保存（ Save ） ] をクリックして、新しいポリシーを保存します。
. 特定のアセットタイプに複数のポリシーがある場合は、ポリシーが評価される順序を変更できます。[ 編集 ] メニューを使用して、ポリシーの順序を変更します。

