---
sidebar: sidebar 
permalink: task_dashboard_example_node_utilization.html 
summary: ストレージノードの利用率を表示するダッシュボードの例。 
keywords: dashboard, widget, custom, example, storage, node, utilization 
---
= ダッシュボードの例：変数を使用したストレージノード利用率


[role="lead"]
ストレージ、ストレージプール、ノード、階層、利用率、レイテンシに変数を使用する Storage Analysis 用のカスタムダッシュボードを作成します。

ダッシュボードに精通していることを推奨しますが、必須ではありません

次の手順では、ストレージ、ストレージプール、ノード、階層、利用率、およびレイテンシに変数を使用する、カスタムの Storage Analysis Overview ダッシュボードを作成します。次の例の変数を使用して、ダッシュボードで使用できる 1 つ以上のウィジェットで表示するアセットや指標をフィルタリングします。これらの変数をフィルタとして使用するウィジェットは、ダッシュボードの変数フィールドに入力した値に従ってフィルタされたコンテンツをオンデマンドで表示するように更新されます。これにより、複数のグラフやグラフをすばやくフィルタして、関心のある特定の領域にドリルダウンできます。

この例の手順に従って、次のようなダッシュボードを作成します。これらのウィジェットを変更したり、任意の数のウィジェットを追加して、選択したデータを強調表示することができます。

.手順
. 新しいダッシュボードを作成し、「 Analysis ： Storage Overview 」という名前を付けるか、同様に説明する名前を付けます。
. 変数（ Variable ）ドロップダウンをクリックし、テキスト変数タイプ（ Text variable type ）を選択します。デフォルトでは、変数の名前は $var1 です。$var1 をクリックして名前を編集し、 $storage に変更してから、チェックマークをクリックして変数を保存します。$node 、 $pool 、および $volume のテキスト変数を作成する場合にも同じ手順を繰り返します。
. 上記の手順を繰り返して、 $utilization および $latency という名前の数値タイプ変数を作成します。
. 変数（ Variable ）ドロップダウンをクリックし、階層（ Tier ）アノテーションを検索します。$tier という名前の変数を作成する場合に選択します。
+
変数はいつでも追加できますが、あらかじめ作成しておくと簡単に作成できるため、作成時にすべてのウィジェットで使用できるようになります。

. ウィジェットを追加するには、ウィジェットのドロップダウンをクリックし、折れ線グラフまたは面グラフウィジェットのいずれかを選択します。ウィジェットに「 Node Utilization 」という名前を付けます。ストレージアセットのタイプをクリックして、ストレージノードに変更します。グラフデータの使用状況 - 合計を選択します。
. フィルタを追加するには、 [Filter by+] ボタンをクリックします。ストレージを検索して選択し、任意のをクリックして $storage 変数を選択します。
. [+] ボタンをクリックして、 [ 名前 ] に別のフィルタを追加します。変数を $node に設定します。
+
アノテーション名フィルタには、さまざまな変数を割り当てることができます。ウィジェットのオブジェクトに応じて、名前と変数のペアを最下位レベルで使用します。例：

+
** ノードに焦点を当てたウィジェットの名前フィルタに $node 変数を割り当てることができます。
** プールに焦点を当てたウィジェットの名前フィルタに $pool 変数を割り当てることができます。


. [+] ボタンをクリックして、 [ 使用状況 - 合計（ % ） ] の別のフィルタを追加します。変数を $utilization に設定します。
. [ ロールアップ ] フィールドの後にある [X] をクリックして、フィールドを折りたたみます。
. [ トップ 5 を表示 ] を選択し、 [ 保存 ] をクリックしてウィジェットを保存し、ダッシュボードに戻ります。


ウィジェットは次のようになります。

別の折れ線グラフウィジェットまたは面グラフウィジェットをダッシュボードに追加します。アセットのタイプとしてストレージノードを選択し、グラフ化する指標として Latency - Total を選択します。

. フィルタ条件 + ボタンをクリックして、ストレージ： $storage および名前： $node のフィルタを追加します。
. Latency - Total のフィルタを追加して、 $latency 変数を選択します。
. ウィジェットに「 Node Latency 」と名前を付けて保存します。


サポートテーブルを追加すると、作成したグラフの詳細（最大ノード利用率や平均ノード利用率など）を表示できます。ダッシュボードに表ウィジェットを追加し、アセットタイプとしてストレージノードを選択し、ストレージ用のフィルタを作成します。ストレージのフィルタ： $storage 、名前： $node 、利用率 - 合計： $utilization 。

. Utilization - Max 、 Utilization - Total 、またはその他の目的の列の列をテーブルに追加します。
. ウィジェットに「 Node Peak and Avg Utilization 」という名前を付けて保存します。


同じ手順を繰り返して、必要に応じて Latency - Max 、 Latency - Total 、またはその他の列を表示するノードレイテンシの表を作成します。ダッシュボードを全体的に表示するには、次の一部またはすべてのグラフウィジェットと表ウィジェットを追加します。

* チャート表
* ストレージプール利用率ストレージプールのピークと平均利用率
* ストレージプールのスループットストレージプールの最大スループットと平均スループット
* ボリュームレイテンシボリュームのピークと平均レイテンシ
* ボリューム IOPS ボリュームの最大ピーク IOPS と平均 IOPS


ウィジェットは、ダッシュボードのどの位置にでも移動したり、サイズを変更したりできます。完了したら、必ずダッシュボードを保存してください。

最後のダッシュボードは次のようになります。

変数を使用して、ダッシュボード内の特定のアセットに絞り込むことができます。変数フィールドに値を入力すると、ウィジェットが自動的に更新されて変数が反映されます。たとえば、 $utilization 変数フィールドに「 15 」を入力すると、その変数 update を使用するウィジェットは、合計利用率が 15% を超えるアセットのみを表示します。

ノード利用率ウィジェットに表示されたすべてのノードのうち上位 5 つを表示：

ノード利用率ウィジェットに使用率が 15% 以上のノードが表示されている場合：

ウィジェットを作成する際は、次の点に注意してください。

* 階層変数 $tier は、 Tier アノテーションでアノテートされているリソースのみに影響します。
* ウィジェットが指定した変数を受け入れるように設計されているかどうかによっては、すべてのフィルタがすべてのウィジェットに影響するわけではありません。
* 数値変数は、指定された値以上の値として適用されます。


ストレージ階層のどのレベルのウィジェットでも、ウィジェットの実行元のアセットに対して変数が有効であれば、任意の変数をフィルタとして使用できます。ノードレベルからストレージプールからボリュームウィジェットに移動すると、フィルタとして割り当てる変数が増えます。たとえば、ストレージノードレベルのウィジェットでは、ストレージ変数と名前変数をフィルタとして割り当てることができます。ストレージプールレベルでは、ストレージ、ノード、ストレージプール、および名前のすべてを使用できます。必要に応じて変数を割り当て、スタック内の最下位レベルで $name 変数を使用します。これにより、ウィジェットを実行している実際のアセット名で $ name 変数をフィルタできます。
