---
sidebar: sidebar 
permalink: task_kubernetes_operator_proxy.html 
keywords: telegraf, installation, install, agent, telegraf agent 
summary: 'Cloud Insights はをサポートします link:https://docs.influxdata.com/telegraf/v1.19/["Tegraf"] 統合データを収集するエージェントであり、 Windows 、 Linux 、 macOS 、および Kubernetes 上で設定できます。' 
---
= データを収集するエージェントの設定


[role="lead"]
カスタム / プライベート Docker リポジトリを使用してプロキシを設定する 2021 年 12 月 10 日に本番稼働に入った CI 導入以降、 CR で監視オペレータのプロキシを設定できます

kubectl -n NetApp-monitoring edit agent agent-monitoring netapp を選択します

このファイルの spec: セクションで、次のコードブロックを追加します

仕様： proxy ： isAuProxyEnabled ： <true または false> isTelegraafProxyEnabled ： <true または false> isFluentbitProxyEnabled ： <true または false> パスワード： < プロキシのパスワード、オプション > port ： < プロキシのポート > サーバ： < プロキシのサーバのユーザ名： < プロキシのユーザ名、オプション > noProxy ： < プロキシをバイパスする必要がある IP または解決可能なホスト名のカンマ区切りリスト > カスタム / プライベート Docker リポジトリを使用すると、 Docker シークレットが取得されます

kubectl -n NetApp-monitoring get secret Docker -o yaml

（前述のコマンドの出力から .dockerconfigjson の値をコピーペースト） Docker シークレットをデコードします

echo<paste from 手順 1 above > | base64 -d このコマンドの出力は、次の JSON 形式になります。 ｛ "auths" ： ｛ "docd.<cluster> .cloudinsights.netapp.com" ： ｛ "username" ： "<tenant id>" 、 "password" ： "< CI API キーであるパスワード > 、 "auth" ： "< エンコードされたユーザ名：基本パスワード認証キー。Docker リポジトリへのログインには Docker 「 } 」が使用されています

Docker ログイン Docker 。 <cluster> .cloudinsights.netapp.com （手順 2 から） -u < ユーザ名を手順 #2 のパスワード： < 手順 #2 からのパスワード： Cloud Insights からオペレータの Docker イメージを取得します

Docker は Docker をプルします。 <cluster> .cloudinsights.netapp.com/netapp-monitoring:<version>

次のコマンドを使用して <version> フィールドを確認します。

kubectl -n NetApp-monitoring get deployment monitoring operator|grep " image ： " オペレータ用の Docker イメージをプライベート / エンタープライズ用の Docker レジストリにプッシュします

社内ポリシーに従って、プライベート / ローカル / エンタープライズ Docker リポジトリにコードをプッシュするオープンソースの依存関係をすべてプライベート Docker レジストリにダウンロードします

次のオープンソースイメージをダウンロードする必要があります。 dock.io/テレ グラム :1.19.3 GCR.io/kubebbuilder/kube-RBAC プロキシ : v0.5.0 k81.gcr.io/kube-state-metrics/kube-state-metrics : v2.1.0

FLUENT ビットが有効になっている場合： Docker .IO/FLUENT ビット： 1.7.8 Docker .IO/Kubernetes -event-exporter ： 0.10 エージェント CR を編集して新しい Docker repo の場所を反映させ、自動アップグレードを無効にします（有効な場合）。

kubectl -n NetApp-monitoring edit agent agent-monitoring netapp を選択します

enableAutoUpgrade ： false docd-repo ： <dockerRepoSecret ： <optional ： enterprise-corp Docker repo の Docker シークレットの名前。このシークレットは、同じネームスペース内の k8s クラスタにすでに作成されている必要があります。 >

spec: セクションで ' 次の変更を行います

仕様 : テレグラム : -name: KSM 置換 : -key: k81.gcr.io 値 : < 上記の "Docker - repa" フィールドと同じ >
