---
sidebar: sidebar 
permalink: task_h2_perf_policy.html 
keywords: performance policy, how to, policy 
summary: パフォーマンスポリシーを作成しています。 
---
= パフォーマンスポリシーを使用してリソースを監視する方法


[role="lead"]
パフォーマンスポリシーを作成して、ネットワーク内のリソースに関連する問題についてユーザに通知するアラートをトリガーするしきい値を設定します。

たとえば、パフォーマンスポリシーを作成して、ストレージプールで使用されている合計容量が 60GB を超えたときにアラートを受け取ることができます。



== パフォーマンスポリシーを作成する

次の手順では、 Tier 1 データストアの使用容量が 600GB を超えた場合にアラートを送信するパフォーマンスポリシーを作成する方法について説明します。

.手順
. Cloud Insights を開きます
. [ * 管理 ] 、 [ パフォーマンスポリシー * ] の順にクリックします
+
ポリシーはオブジェクト別に表示され、各オブジェクトのリストに表示されている順序で評価されます。

. [* + Performance Policy] をクリックします。
+
.. ポリシー名を追加します
.. オブジェクトタイプ（データストア）の追加
.. アノテーション「 Tier 」と入力します
.. アノテーション値 = 階層 1
.. ウィンドウ = 最初のオカレンスの後に適用します
.. 重大度 = 警告の場合
.. E メール受信者には、グローバルリストを使用することも、各ポリシーの特定のリストを使用することもできます
.. しきい値を作成します。 Capacity Used > 600 GB
.. 最初のアラートのあとに処理を停止するようにポリシーを設定するには、このチェックボックスをオンにします。






== パフォーマンスポリシーの違反を監視する

パフォーマンスポリシー違反は、 Violations Dashboard を使用して表示できます。ダッシュボードには、ネットワークで発生したすべての違反が表示されるため、対処が必要な問題を簡単に特定できます。

ダッシュボード（ Dashboard ） > 違反（ Violation ） * をクリックし、違反ダッシュボード（ Violations Dashboard ）にアクセスします。

違反をデバイス、ポリシー名、日付、時刻、重大度でフィルタリングできます。 など。

Time 列をクリックして、に移動します

違反 ID または概要フィールドでハイライト表示されているデバイスをクリックすると、違反を生成したデバイスのアセットページが開きます。

アセットページの違反セクションには、アセットについて発生したすべての違反が表示されます。エキスパートビューで指標を選択すると、違反を視覚的に確認できます。



=== 違反の通知

ポリシー違反が発生した場合に E メール通知を送信するようにパフォーマンスポリシーを設定できます。

グローバル E メールリストに受信者を追加するには、 [*Admin] > [Notifications] の順にクリックし、受信者の E メールアドレスをカンマで区切って入力します。パフォーマンスポリシーのしきい値違反のアラートとして送信される E メールは、リスト内のすべての受信者に送信されます。ポリシーを設定するときに、特定のポリシーのグローバルリストを無効にすることができます。
