---
sidebar: sidebar 
permalink: task_view_configured_data_collectors.html 
keywords: acquisition, AU, data collector, collector, bulk edit, postpone polling, resume polling 
summary: 概要。 
---
= 設定済みデータコレクタの管理
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
Installed Data Collectors ページから、 Cloud Insights 用に設定されているデータコレクタにアクセスできます。このページを使用して、既存のデータコレクタを変更できます。

.手順
. Cloud Insights メニューで、 * Admin > Data Collector* をクリックします
+
Available Data Collectors 画面が表示されます。

. [ インストール済みデータコレクタ * ] をクリックします
+
インストールされているすべてのデータコレクタのリストが表示されます。リストはコレクタを提供します
名前、ステータス、コレクタがアクセスしているIPアドレス、およびデータが最後に取得された日時
Aデバイスから。この画面で実行できる操作には、次のものがあります。

+
** ポーリングの制御
** データコレクタのクレデンシャルを
** データコレクタのクローンを作成






== Data Collector ポーリングの制御

データコレクタに変更を加えた後、すぐにポーリングして確認することができます
変更を加えたり、データコレクタのデータ収集を延期したりすることができます。
あなたが問題に取り組んでいる間、3日か5日。

.手順
. Cloud Insights メニューで、 * Admin > Data Collector* をクリックします
. [ インストール済みデータコレクタ * ] をクリックします
. 変更する Data Collector の左側にあるチェックボックスをオンにします
. ［ * 一括処理 * ］ をクリックして、実行するポーリングアクションを選択します。
+
複数のデータコレクタに対して一括アクションを同時に実行できます。データを選択します
をクリックし、* Bulk Action *メニューから実行するアクションを選択します。





== データコレクタ情報の編集

既存のデータコレクタの設定情報を編集できます。

.単一のデータコレクタを編集するには、次
. Cloud Insights メニューで、 * Admin > Data Collector* をクリックして、インストールされているデータコレクタのリストを開きます。
. 変更するデータコレクターの右にあるオプションメニューで、 * 編集 * をクリックします。
+
[Edit Collector] ダイアログが開きます。

. 変更内容を入力し、 * テスト構成 * をクリックして新しい構成をテストするか、 * 保存 * をクリックして構成を保存します。


複数のデータコレクタを編集することもできます。

. 変更する各データコレクタの左側にあるチェックボックスをオンにします。
. 「 * Bulk Actions * 」ボタンをクリックし、「 * Edit * 」を選択して、「 Edit Data Collector 」ダイアログを開きます。
. 上記のようにフィールドを変更します。
+

NOTE: 同じベンダーとモデルのデータコレクタを選択し、同じ Acquisition Unit に配置する必要があります。

+
複数のデータコレクタを編集する場合、 Data Collector Name フィールドには「 Mixed 」と表示され、編集できません。ユーザー名やパスワードなどの他のフィールドには「混在」と表示され、編集できます。選択したデータコレクタ間で同じ値を共有するフィールドには、現在の値が表示され、編集できます。

+
複数のデータコレクタを編集する場合、 * テスト設定 * ボタンは使用できません。





== データコレクタのクローニング

クローン機能を使用すると、同じクレデンシャルを持つデータソースを簡単に追加できます
および属性を別のデータソースとして使用できます。クローニングを使用すると、複数のを簡単に構成できます
同じデバイスタイプのインスタンス。

.手順
. Cloud Insights メニューで、 * Admin > Data Collector* をクリックします。
. [ インストール済みデータコレクタ * ] をクリックします。
. コピーするデータコレクタの左側にあるチェックボックスをオンにします。
. 選択したデータコレクターの右にあるオプションメニューで ' * クローン * をクリックします
+
Clone Data Collector （クローンデータ収集）ダイアログが表示されます。

. 必須フィールドに新しい情報を入力します。
. [ 保存（ Save ） ] をクリックします。


.完了後
他のすべての属性と設定がクローニング処理によってコピーされ、新しいデータコレクタが作成されます。



== データコレクタに対して一括操作を実行する

複数のデータコレクタの一部の情報を同時に編集できます。この機能を使用すると、複数のデータコレクタでポーリングの開始、ポーリングの延期、およびポーリングの再開を行うことができます。また、複数のデータコレクタを削除することもできます。

.手順
. Cloud Insights メニューで、 * Admin > Data Collector* をクリックします
. [ インストール済みデータコレクタ * ] をクリックします
. 変更するデータコレクタの左側にあるチェックボックスをオンにします。
. 右側のオプションメニューで、実行するオプションをクリックします。


.完了後
選択した操作がデータコレクタで実行されます。データコレクタを削除するように選択すると、アクションを適合させる必要があるダイアログが表示されます。
