---
sidebar: sidebar 
permalink: task_dc_na_astra_datastore.html 
summary: ネットアップの Astra データストアを設定 
keywords: data collector, queries, create, astra, ads 
---
= NetApp Astra データコレクタ


[role="lead"]
ネットアップの Astra データストアデータソースは、 1 つの Astra データストア（ ADS ）クラスタの構成データとパフォーマンスデータを監視してレポートします。



== 用語集

Cloud Insights は、このコレクタからインベントリとパフォーマンスのデータを取得します。取得したアセットのタイプごとに、そのアセットに使用される最も一般的な用語が表示されます。このデータコレクタを表示またはトラブルシューティングするときは、次の用語に注意してください。

[cols="2*"]
|===
| ベンダー / モデルの用語 | Cloud Insights の用語 


| AstraDSVolume | 内部ボリューム 


| AstraDSNodeInfo.status.drives | ディスク 


| AstraDSNodeInfo | ストレージノード 


| AstraDSExportPolicy の順にクリックします | 共有 / 共有イニシエータ 


| AstraDSCluster | ストレージ 
|===


== 設定

[cols="2*"]
|===
| フィールド | 説明 


| Kubernetes API の IP アドレス | Kubernetes API サーバの IP アドレス 


| Kubernetes API ポート | Kubernetes API サーバのポート 


| Kubernetes API トークン | Base64 でエンコードされた Kubernetes API トークン 


| クラスタ名を含める | 監視するクラスタ名をカンマで区切ったリスト。Empty = すべてのクラスタを監視します 
|===


== 詳細設定

[cols="2*"]
|===
| フィールド | 説明 


| インベントリポーリング間隔（分） | インベントリのポーリング間隔。デフォルトは 60 分です。 


| パフォーマンスポーリング間隔（秒） | パフォーマンスのポーリング間隔デフォルトは 300 秒です。 


| ADS メトリクスエンドポイント | ADS クラスタメトリックエンドポイント（不要） 
|===


== トラブルシューティング

この Data Collector の追加情報は、から入手できます link:concept_requesting_support.html["サポート"] ページまたはを参照してください link:https://docs.netapp.com/us-en/cloudinsights/CloudInsightsDataCollectorSupportMatrix.pdf["Data Collector サポートマトリックス"]。
