---
sidebar: sidebar 
permalink: task_h2_minrisk_thin.html 
keywords: thin provisioning, how to, policy 
summary: シンプロビジョニングの処理を最小限に抑える。 
---
= シンプロビジョニングのリスクの最小化の概要


[role="lead"]
今日のハイブリッド IT データセンターでは、管理者は、シンプロビジョニングなどの容量効率化テクノロジを使用して割り当てを制御し、かつて使用できなかった容量を活用することで、物理的な範囲を超えたリソース利用率を拡大する必要があります。

Cloud Insights は、 IT サービススタック内の複数のシンプロビジョニングレイヤにおいて、従来からほぼリアルタイムの使用容量と利用率の詳細を提供します。オーバーサブスクリプションリスクを適切に管理できないと、ビジネスに不必要なダウンタイムが発生する可能性があります。



== ストレージプールを監視しています

ストレージプールの各ランディングページには、オーバーサブスクリプション率、関連するリソース、 LUN とディスクの利用率、ストレージプールで発生したポリシー違反や違反が表示されます。

ストレージプールのランディングページを使用して、仮想インフラをサポートしている物理資産に潜在的な問題がないか確認します。容量と容量の比率のトレンドを 30 日間にわたって追跡したり、カスタムの期間を使用したりできます。ストレージプールのステータスを監視するには、以降のセクションのデータに注意してください。

「 * 概要 * 」セクションでは、以下について説明します。

* ストレージプールの容量情報には、物理容量とオーバーコミット容量が含まれます。
* アグリゲートがオーバーサブスクライブされているかどうかと、その量による
* 発生したポリシー違反
* LUN の利用率については、「ストレージリソース」セクションで確認してください
* 「ディスク」セクションでは、ストレージプールを構成する個々のディスクについて説明します
* 「リソース * 」セクションを使用して、 VMDK と LUN の相関関係を理解し、ストレージと VM 間のアプリケーションパスを把握します
* Violations * セクションを使用して、ストレージプールに設定されたパフォーマンスポリシーへの違反を特定します。




== データストアの監視

データストアランディングページでは、オーバーサブスクリプション率、 LUN とディスクの利用率、関連するリソース、データストアで発生したポリシーの違反を確認できます。

このランディングページでは、仮想インフラの問題を特定できます。容量と容量の比率のトレンドを追跡することで、容量の変化を予測できます。

「 * 概要 * 」セクションでは、以下について説明します。

* データストアの容量情報には、物理容量とオーバーコミット容量が含まれます。
* オーバーコミット容量の割合。
* レイテンシ、 IOPS 、およびスループットの指標。


「 * VMDKs * 」セクションには、仮想ディスクの容量とパフォーマンスが表示されます。「ストレージリソース」セクションには、データストアに関連する、内部ボリュームの使用済み容量とパフォーマンス指標が表示されます。「 * Resources 」セクションでは、 VMDK と LUN の相関関係を理解し、ストレージと VM のアプリケーションパスを把握できます。



== シンプロビジョニング環境を監視するダッシュボードを作成する

Loud Insights の柔軟性に優れたダッシュボードウィジェット設計とグラフ作成オプションにより、容量の使用状況と使用率を詳細に分析し、シンプロビジョニングされたデータセンターインフラストラクチャのリスクを最小限に抑えるための戦略的情報を入手できます。

監視するデータストアとストレージプールの情報へのアクセスを提供するダッシュボードを作成できます。



=== ダッシュボードを使用したデータストア情報へのアクセス

仮想インフラ内で監視するデータにすばやくアクセスできるダッシュボードの作成が必要になることがあります。ダッシュボードには、次のようなウィジェットを含めることができます。データストアのオーバーコミット率に基づく上位 10 個のデータストアを特定するウィジェットや、データストアの容量データを表示するウィジェットを指定することができます。ダッシュボードでは、変数を使用して、使用済み容量が 80% を超えているデータストアとオーバーコミットされたデータストアを表示します。

画像： top_10_overcommit.png



== パフォーマンスポリシーを使用してシンプロビジョニングのリスクを軽減する

仮想インフラのしきい値を超えたときにアラートを生成するには、パフォーマンスポリシーを作成する必要があります。アラートを使用すると、原因が処理を中断または停止する前に、環境内の変更に対応できます。

仮想インフラの監視に役立つポリシーは次のとおりです。

* データストア * データストア容量を厳密に監視するポリシーを作成できます。

* 容量比率 - オーバーコミット
* 容量比率 - 使用済み
* Capacity - 使用済みです
* 容量 - 合計


* ストレージプール * シンプロビジョニング環境でストレージプール容量の停止から保護するポリシーを作成できます。

* プロビジョニング済み容量
* 使用済みパフォーマンス容量
* 容量比率 - オーバーコミット
* 容量比率 - 使用済み


これらのポリシーをさらに拡張して仮想インフラの容量を監視するには、次のアセット用のポリシーを追加で作成します。

* 内部ボリューム
* LUN
* ディスク
* VMDK
* 仮想マシン


ポリシーはアノテーションを使用して設定できます。アプリケーションをサポートする特定のアセットに同じアノテーションを割り当てる。たとえば、データストアにアノテーションを割り当てたり、シンプロビジョニングアプリケーションのストレージプールにアノテーションを割り当てたりできます。

本番環境用の Production というアノテーション、開発環境用の Development などのアノテーションを設定することができます。アセットがサポートしているアプリケーションのタイプに応じて、しきい値や警告の重要度を変更することができます。

たとえば、本番環境アプリケーションのデータストアに対するしきい値の違反があった場合、重大な警告が表示される可能性があり、同じ開発環境への違反があった場合は警告しか表示されないことがあります。

定義済みのポリシーにアノテーションを組み込むことで、重要でない資産に関する不要なアラートの生成を軽減できます。



== ストレージプールのパフォーマンスポリシーの作成

パフォーマンスポリシーを作成して、ストレージプールのアセットのしきい値を超えたときに通知するアラートをトリガーすることができます。

* 作業を開始する前に


この手順は、ストレージプールがシンプロビジョニングされていることを前提としています。

* このタスクについて


停止につながる可能性のあるストレージプールの変更を監視してレポートするポリシーを作成する。シンプロビジョニングされた物理ストレージプールの場合は、物理容量を監視してオーバーコミット率を監視する必要があります。

* 手順
+
.. Cloud Insights メニューで、 * Manage > Performance Policies * の順にクリックします
+
パフォーマンスポリシーページが表示されます。ポリシーはオブジェクト別に表示され、リストに表示されている順序で評価されます。通知が有効になっている場合（ * Admin > Notifications * ）、パフォーマンスポリシーに違反したときに E メールを送信するように Insight を設定できます。

.. パフォーマンスポリシーをクリックして新しいポリシーを作成します
.. [ * ポリシー名 * ] に、ポリシーの一意の名前を入力します
.. [ タイプ * のオブジェクトに適用 ] で [ ストレージプール ] を選択します
.. [ * Apply after window of * ] に、最初のオカレンスを入力する。
.. [* （ * ） ] に重大度 * を入力します
.. しきい値を超えたときに通知を受け取る E メール受信者を設定します。
+
デフォルトでは、ポリシー違反に関する E メールアラートはグローバル E メールリストの受信者に送信されます。この設定を上書きして、特定のポリシーのアラートを特定の受信者に送信するように設定することができます。

+
リンクをクリックして受信者リストを開き、 [+] ボタンをクリックして受信者を追加します。このポリシーに関する違反のアラートがリスト内のすべての受信者に送信されます。

.. * 次のいずれかに該当する場合はアラートを作成します。 * 容量比率を入力してください - 使用済み >85%


* 結果


この構成では、ストレージプールの物理容量の 85% を超える容量が使用されている場合に、重大な警告メッセージが送信されます。物理メモリの 100% を使用すると、アプリケーションに障害が発生します。



== データストアのパフォーマンスポリシーの作成

監視しているストレージプールに関連するデータストアに関連付けられている指標のしきい値を設定したパフォーマンスポリシーを作成できます。

デフォルトでは、パフォーマンスポリシーは作成時に指定したタイプのすべてのデバイスに適用されます。特定のデバイスまたはデバイスセットのみをパフォーマンスポリシーに含める場合は、アノテーションを作成します。

. 作業を開始する前に


パフォーマンスポリシーでアノテーションを使用する場合、ポリシーを作成する前にアノテーションが存在している必要があります。

監視しているデータストアが設定したしきい値を超えたときに通知するパフォーマンスポリシーを作成します。システムには、ニーズに合わせたグローバルポリシーがすでに含まれている場合があります。アノテーションを使用するポリシーでは、特定のデータストアに集中できます。

.手順
. Cloud Insights ツールバーで、 * 管理 > パフォーマンスポリシー * をクリックします
. [* + Performance Policy] をクリックします
. 「ポリシー名」を追加
+
オブジェクトの他のすべてのポリシーとは異なる名前を使用する必要があります。たとえば、内部ボリュームの「 Latency 」という名前の 2 つのポリシーを使用することはできませんが、内部ボリュームの「 Latency 」ポリシーとデータストアの「 Latency 」ポリシーを使用できます。ベストプラクティスとしては、オブジェクトタイプに関係なく、すべてのポリシーに一意の名前を常に使用することを推奨します。

. オブジェクトタイプとして「 Datastore 」を選択します
. [ 最初の発生 ] をクリックします。
. [ * ポリシー名 * ] に、ポリシーの一意の名前を入力します
. で * タイプ * のオブジェクトに適用する場合は、データストアを選択します
. 注釈付き * （ With Annotation ）で、注釈の名前を選択します
. [ * 注釈値 * （ * Annotation Value * ） ] で目的の値を選択します
. [ * Apply after window of * ] に、最初のオカレンスを入力する
. [* （ * ） ] に重大度 * を入力します
. E メール受信者を設定
. * Create alert * に Capacity Ratio over Commit > 150 を入力します
. しきい値を追加するには、 [* + しきい値 * （ * + Threshold ） ] をクリックします。これには、容量の合計や使用容量

